rails_tutorial: "https://www.railstutorial.org/"
rails: "https://rubyonrails.org/"
michaelhartl: "https://www.michaelhartl.com/"
rails_news: "https://news.railstutorial.org/"
rails_contact: "https://www.railstutorial.org/#contact"
rails_help: "https://github.com/mhartl/sample_app_6th_ed/blob/main/HELP.md"
rails_book: "https://www.railstutorial.org/book"
learn_enough: "https://www.learnenough.com/"
rails_screen_casts: "https://screencasts.railstutorial.org/"
valid_email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
minimum_email: 20
maximum_email: 255
maximum_name: 50
minimum_pass: 6
gravatar_email: "https://gravatar.com/emails"
gravatar_url: "https://secure.gravatar.com/avatar/#"
avt_size: 50
items_page: 8
